const mumbaiLocalTrainStations = [
    // Western line
    "Churchgate",
    "Marine Lines",
    "Charni Road",
    "Grant Road",
    "Mumbai Central",
    "Mahalaxmi",
    "Lower Parel",
    "Elphinstone Road",
    "Dadar",
    "Matunga",
    "Mahim",
    "Bandra",
    "Khar Road",
    "Santacruz",
    "Vile Parle",
    "Andheri",
    "Jogeshwari",
    "Goregaon",
    "Malad",
    "Kandivali",
    "Borivali",
    "Dahisar",
    "Mira Road",
    "Bhayander",
    "Naigaon",
    "Vasai Road",
    "Nallasopara",
    "Virar",
    // Harbour line
    "Chhatrapati Shivaji Terminus (CST)",
    "Masjid",
    "Sandhurst Road",
    "Dockyard Road",
    "Reay Road",
    "Cotton Green",
    "Sewri",
    "Wadala Road",
    "GTB Nagar",
    "Chunabhatti",
    "Kurla",
    "Tilak Nagar",
    "Chembur",
    "Govandi",
    "Mankhurd",
    "Vashi",
    "Sanpada",
    "Juinagar",
    "Nerul",
    "Seawoods – Darave",
    "CBD Belapur",
    "Kharghar",
    "Mansarovar",
    "Khandeshwar",
    "Panvel",
    // Central line
    "Chhatrapati Shivaji Terminus (CST)",
    "Masjid",
    "Sandhurst Road",
    "Byculla",
    "Chinchpokli",
    "Currey Road",
    "Parel",
    "Dadar",
    "Matunga",
    "Sion",
    "Kurla",
    "Vidyavihar",
    "Ghatkopar",
    "Vikhroli",
    "Kanjurmarg",
    "Bhandup",
    "Nahur",
    "Mulund",
    "Thane",
    "Kalwa",
    "Mumbra",
    "DivA",
    "Kopar",
    "Dombivli",
    "Thakurli",
    "Kalyan",
    "Vitthalwadi",
    "Ulhasnagar",
    "Ambernath",
    "Badlapur",
    "Vangani",
    "Shelu",
    "Neral",
    "Bhivpuri Road",
    "Karjat",
    "Palasdari",
    "Kelavli",
    "Dolavli",
    "Lowjee",
    "Kharpada",
    "Khopoli"
];
export { mumbaiLocalTrainStations };
